name: Auto commit

on:
  schedule:
    - cron: '15 4,8,15 * * 0-2'
    - cron: '0 8-20 * * 1-5'
    - cron: '10 3-11 4-20 * *'

    # Tháng 1
    - cron: '12 1 * 1 *'
    - cron: '45 6 * 1 *'
    - cron: '28 15 * 1 *'
    
    # Tháng 2
    - cron: '10 2 * 2 *'
    - cron: '38 9 * 2 *'
    - cron: '59 20 * 2 *'
    
    # Tháng 3
    - cron: '5 3 * 3 *'
    - cron: '50 10 * 3 *'
    - cron: '30 18 * 3 *'
    
    # Tháng 4
    - cron: '0 4 * 4 *'
    - cron: '22 11 * 4 *'
    - cron: '58 17 * 4 *'
    
    # Tháng 5
    - cron: '19 5 * 5 *'
    - cron: '40 12 * 5 *'
    - cron: '33 21 * 5 *'
    
    # Tháng 6
    - cron: '8 6 * 6 *'
    - cron: '41 13 * 6 *'
    - cron: '27 22 * 6 *'
    - cron: '00 18 * 6 *'
    
    # Tháng 7
    - cron: '13 7 * 7 *'
    - cron: '48 14 * 7 *'
    - cron: '31 23 * 7 *'
    
    # Tháng 8
    - cron: '17 8 * 8 *'
    - cron: '36 16 * 8 *'
    - cron: '44 19 * 8 *'
    
    # Tháng 9
    - cron: '20 9 * 9 *'
    - cron: '0 17 * 9 *'
    - cron: '57 20 * 9 *'
    
    # Tháng 10
    - cron: '7 10 * 10 *'
    - cron: '30 18 * 10 *'
    - cron: '52 21 * 10 *'
    
    # Tháng 11
    - cron: '14 11 * 11 *'
    - cron: '35 19 * 11 *'
    - cron: '25 22 * 11 *'
    
    # Tháng 12
    - cron: '3 12 * 12 *'
    - cron: '49 15 * 12 *'
    - cron: '26 23 * 12 *'

    # Tháng 1 bổ sung
    - cron: '14 3 * 1 *'
    - cron: '47 9 * 1 *'
    - cron: '3 20 * 1 *'

    # Tháng 2 bổ sung
    - cron: '25 5 * 2 *'
    - cron: '53 14 * 2 *'
    - cron: '11 21 * 2 *'

    # Tháng 3 bổ sung
    - cron: '17 7 * 3 *'
    - cron: '38 12 * 3 *'
    - cron: '44 22 * 3 *'

    # Tháng 4 bổ sung
    - cron: '9 8 * 4 *'
    - cron: '31 13 * 4 *'
    - cron: '56 18 * 4 *'

    # Tháng 5 bổ sung
    - cron: '6 6 * 5 *'
    - cron: '29 11 * 5 *'
    - cron: '41 19 * 5 *'

    # Tháng 6 bổ sung
    - cron: '12 7 * 6 *'
    - cron: '35 10 * 6 *'
    - cron: '50 15 * 6 *'

    # Tháng 7 bổ sung
    - cron: '2 9 * 7 *'
    - cron: '27 14 * 7 *'
    - cron: '53 20 * 7 *'

    # Tháng 8 bổ sung
    - cron: '7 6 * 8 *'
    - cron: '34 13 * 8 *'
    - cron: '45 21 * 8 *'

    # Tháng 9 bổ sung
    - cron: '16 8 * 9 *'
    - cron: '39 12 * 9 *'
    - cron: '55 18 * 9 *'

    # Tháng 10 bổ sung
    - cron: '10 7 * 10 *'
    - cron: '33 11 * 10 *'
    - cron: '49 20 * 10 *'

    # Tháng 11 bổ sung
    - cron: '4 6 * 11 *'
    - cron: '28 15 * 11 *'
    - cron: '52 19 * 11 *'

jobs:
  auto_commit:
    name: 'Auto push a commit to my repo'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create sample file with just timestamp
      run: date +%s >> report.txt
    - name: Commit file
      run: |
          git config --global user.name 'tungnnx'
          git config --global user.email 'tungnnx@users.noreply.github.com'
          git add report.txt
          git commit -am "update code"
          git push
